# TCL File Generated by Component Editor 18.1
# Sat Apr 20 19:48:25 CEST 2024
# DO NOT MODIFY


# 
# AI_Comparer "AI_Comparer" v1.0
#  2024.04.20.19:48:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AI_Comparer
# 
set_module_property DESCRIPTION ""
set_module_property NAME AI_Comparer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AI_Comparer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AI_comparer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AI_FIFO_Basic.v VERILOG PATH AI/Comparer/AI_FIFO_Basic.v
add_fileset_file AI_IDMA.v VERILOG PATH AI/Comparer/AI_IDMA.v
add_fileset_file AI_QCRC64_ISO.v VERILOG PATH AI/Comparer/AI_QCRC64_ISO.v
add_fileset_file AI_QCRC_sum.v VERILOG PATH AI/Comparer/AI_QCRC_sum.v
add_fileset_file AI_av_reader.v VERILOG PATH AI/Comparer/AI_av_reader.v
add_fileset_file AI_av_writer.v VERILOG PATH AI/Comparer/AI_av_writer.v
add_fileset_file AI_buffer.v VERILOG PATH AI/Comparer/AI_buffer.v
add_fileset_file AI_category.v VERILOG PATH AI/Comparer/AI_category.v
add_fileset_file AI_comparer.v VERILOG PATH AI/Comparer/AI_comparer.v TOP_LEVEL_FILE
add_fileset_file AI_core.v VERILOG PATH AI/Comparer/AI_core.v
add_fileset_file AI_core_collect.v VERILOG PATH AI/Comparer/AI_core_collect.v
add_fileset_file AI_crosser.v VERILOG PATH AI/Comparer/AI_crosser.v
add_fileset_file AI_decision.v VERILOG PATH AI/Comparer/AI_decision.v
add_fileset_file AI_decompressor2.v VERILOG PATH AI/Comparer/AI_decompressor2.v
add_fileset_file AI_decompressor4.v VERILOG PATH AI/Comparer/AI_decompressor4.v
add_fileset_file AI_demultiplex.v VERILOG PATH AI/Comparer/AI_demultiplex.v
add_fileset_file AI_error_catcher.v VERILOG PATH AI/Comparer/AI_error_catcher.v
add_fileset_file AI_filter.v VERILOG PATH AI/Comparer/AI_filter.v
add_fileset_file AI_final.v VERILOG PATH AI/Comparer/AI_final.v
add_fileset_file AI_initizer.v VERILOG PATH AI/Comparer/AI_initizer.v
add_fileset_file AI_interrupt.v VERILOG PATH AI/Comparer/AI_interrupt.v
add_fileset_file AI_loader.v VERILOG PATH AI/Comparer/AI_loader.v
add_fileset_file AI_scorer.v VERILOG PATH AI/Comparer/AI_scorer.v
add_fileset_file AI_sort.v VERILOG PATH AI/Comparer/AI_sort.v
add_fileset_file AI_sorter.v VERILOG PATH AI/Comparer/AI_sorter.v
add_fileset_file AI_status.v VERILOG PATH AI/Comparer/AI_status.v
add_fileset_file AI_sum.v VERILOG PATH AI/Comparer/AI_sum.v
add_fileset_file AI_wait.v VERILOG PATH AI/Comparer/AI_wait.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_address address Input 4
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint s0
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender avm_s0_irq irq Output 1


# 
# connection point cmd
# 
add_interface cmd avalon_streaming start
set_interface_property cmd associatedClock clock
set_interface_property cmd associatedReset reset
set_interface_property cmd dataBitsPerSymbol 8
set_interface_property cmd errorDescriptor ""
set_interface_property cmd firstSymbolInHighOrderBits true
set_interface_property cmd maxChannel 0
set_interface_property cmd readyLatency 0
set_interface_property cmd ENABLED true
set_interface_property cmd EXPORT_OF ""
set_interface_property cmd PORT_NAME_MAP ""
set_interface_property cmd CMSIS_SVD_VARIABLES ""
set_interface_property cmd SVD_ADDRESS_GROUP ""

add_interface_port cmd avm_m1_dout data Output 40
add_interface_port cmd avm_m1_ivalid valid Output 1
add_interface_port cmd avm_m1_oready ready Input 1


# 
# connection point data
# 
add_interface data avalon_streaming end
set_interface_property data associatedClock clock
set_interface_property data associatedReset reset
set_interface_property data dataBitsPerSymbol 8
set_interface_property data errorDescriptor ""
set_interface_property data firstSymbolInHighOrderBits true
set_interface_property data maxChannel 0
set_interface_property data readyLatency 0
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data avs_s2_inout data Input 40
add_interface_port data avs_s2_valid valid Input 1
add_interface_port data avs_s2_ready ready Output 1


# 
# connection point qram_data
# 
add_interface qram_data avalon_streaming end
set_interface_property qram_data associatedClock clock
set_interface_property qram_data associatedReset reset
set_interface_property qram_data dataBitsPerSymbol 8
set_interface_property qram_data errorDescriptor ""
set_interface_property qram_data firstSymbolInHighOrderBits true
set_interface_property qram_data maxChannel 0
set_interface_property qram_data readyLatency 0
set_interface_property qram_data ENABLED true
set_interface_property qram_data EXPORT_OF ""
set_interface_property qram_data PORT_NAME_MAP ""
set_interface_property qram_data CMSIS_SVD_VARIABLES ""
set_interface_property qram_data SVD_ADDRESS_GROUP ""

add_interface_port qram_data avm_s2_dout data Input 64
add_interface_port qram_data avm_s2_valid valid Input 1
add_interface_port qram_data avm_s2_ready ready Output 1


# 
# connection point qram_addr
# 
add_interface qram_addr avalon_streaming start
set_interface_property qram_addr associatedClock clock
set_interface_property qram_addr associatedReset reset
set_interface_property qram_addr dataBitsPerSymbol 8
set_interface_property qram_addr errorDescriptor ""
set_interface_property qram_addr firstSymbolInHighOrderBits true
set_interface_property qram_addr maxChannel 0
set_interface_property qram_addr readyLatency 0
set_interface_property qram_addr ENABLED true
set_interface_property qram_addr EXPORT_OF ""
set_interface_property qram_addr PORT_NAME_MAP ""
set_interface_property qram_addr CMSIS_SVD_VARIABLES ""
set_interface_property qram_addr SVD_ADDRESS_GROUP ""

add_interface_port qram_addr avm_m2_dout data Output 32
add_interface_port qram_addr avm_m2_valid valid Output 1
add_interface_port qram_addr avm_m2_ready ready Input 1

