# TCL File Generated by Component Editor 18.1
# Sat Apr 20 19:49:19 CEST 2024
# DO NOT MODIFY


# 
# AI_RAM "AI_RAM" v1.0
#  2024.04.20.19:49:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AI_RAM
# 
set_module_property DESCRIPTION ""
set_module_property NAME AI_RAM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AI_RAM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AI_RAM
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AI_RAM.v VERILOG PATH AI/RAM/AI_RAM.v TOP_LEVEL_FILE
add_fileset_file AI_RAM_avst_loader.v VERILOG PATH AI/RAM/AI_RAM_avst_loader.v
add_fileset_file AI_RAM_sector.v VERILOG PATH AI/RAM/AI_RAM_sector.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_byteenable byteenable Input 4
add_interface_port s1 avs_s1_address address Input 14
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point qram_addr
# 
add_interface qram_addr avalon_streaming end
set_interface_property qram_addr associatedClock clock
set_interface_property qram_addr associatedReset reset
set_interface_property qram_addr dataBitsPerSymbol 8
set_interface_property qram_addr errorDescriptor ""
set_interface_property qram_addr firstSymbolInHighOrderBits true
set_interface_property qram_addr maxChannel 0
set_interface_property qram_addr readyLatency 0
set_interface_property qram_addr ENABLED true
set_interface_property qram_addr EXPORT_OF ""
set_interface_property qram_addr PORT_NAME_MAP ""
set_interface_property qram_addr CMSIS_SVD_VARIABLES ""
set_interface_property qram_addr SVD_ADDRESS_GROUP ""

add_interface_port qram_addr avm_s1_dout data Input 32
add_interface_port qram_addr avm_s1_valid valid Input 1
add_interface_port qram_addr avm_s1_ready ready Output 1


# 
# connection point qram_data
# 
add_interface qram_data avalon_streaming start
set_interface_property qram_data associatedClock clock
set_interface_property qram_data associatedReset reset
set_interface_property qram_data dataBitsPerSymbol 8
set_interface_property qram_data errorDescriptor ""
set_interface_property qram_data firstSymbolInHighOrderBits true
set_interface_property qram_data maxChannel 0
set_interface_property qram_data readyLatency 0
set_interface_property qram_data ENABLED true
set_interface_property qram_data EXPORT_OF ""
set_interface_property qram_data PORT_NAME_MAP ""
set_interface_property qram_data CMSIS_SVD_VARIABLES ""
set_interface_property qram_data SVD_ADDRESS_GROUP ""

add_interface_port qram_data avm_m1_dout data Output 64
add_interface_port qram_data avm_m1_valid valid Output 1
add_interface_port qram_data avm_m1_ready ready Input 1


# 
# connection point dma
# 
add_interface dma avalon_streaming end
set_interface_property dma associatedClock clock
set_interface_property dma associatedReset reset
set_interface_property dma dataBitsPerSymbol 8
set_interface_property dma errorDescriptor ""
set_interface_property dma firstSymbolInHighOrderBits true
set_interface_property dma maxChannel 0
set_interface_property dma readyLatency 0
set_interface_property dma ENABLED true
set_interface_property dma EXPORT_OF ""
set_interface_property dma PORT_NAME_MAP ""
set_interface_property dma CMSIS_SVD_VARIABLES ""
set_interface_property dma SVD_ADDRESS_GROUP ""

add_interface_port dma avs_s4_valid valid Input 1
add_interface_port dma avs_s4_data data Input 32
add_interface_port dma avs_s4_endofpacket endofpacket Input 1
add_interface_port dma avs_s4_startofpacket startofpacket Input 1
add_interface_port dma avs_s4_ready ready Output 1

