# TCL File Generated by Component Editor 18.1
# Sat Apr 20 20:05:23 CEST 2024
# DO NOT MODIFY


# 
# BLE_UART "BLE_UART" v1.0
#  2024.04.20.20:05:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module BLE_UART
# 
set_module_property DESCRIPTION ""
set_module_property NAME BLE_UART
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME BLE_UART
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL BLEUART
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file BLE.v VERILOG PATH BLE/BLE.v TOP_LEVEL_FILE
add_fileset_file BLEUART_FIFO_basic.v VERILOG PATH BLE/BLEUART_FIFO_basic.v
add_fileset_file BLEUART_av.v VERILOG PATH BLE/BLEUART_av.v
add_fileset_file BLEUART_baudtick.v VERILOG PATH BLE/BLEUART_baudtick.v
add_fileset_file BLEUART_error_catcher.v VERILOG PATH BLE/BLEUART_error_catcher.v
add_fileset_file BLEUART_fifo_in.v VERILOG PATH BLE/BLEUART_fifo_in.v
add_fileset_file BLEUART_fifo_out.v VERILOG PATH BLE/BLEUART_fifo_out.v
add_fileset_file BLEUART_recv_byte.v VERILOG PATH BLE/BLEUART_recv_byte.v
add_fileset_file BLEUART_trans_byte.v VERILOG PATH BLE/BLEUART_trans_byte.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_address address Input 3
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint s0
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq avm_s0_irq irq Output 1


# 
# connection point UART
# 
add_interface UART conduit end
set_interface_property UART associatedClock clock
set_interface_property UART associatedReset reset
set_interface_property UART ENABLED true
set_interface_property UART EXPORT_OF ""
set_interface_property UART PORT_NAME_MAP ""
set_interface_property UART CMSIS_SVD_VARIABLES ""
set_interface_property UART SVD_ADDRESS_GROUP ""

add_interface_port UART uart_tx tx Output 1
add_interface_port UART uart_rx rx Input 1


# 
# connection point bgpio
# 
add_interface bgpio conduit end
set_interface_property bgpio associatedClock clock
set_interface_property bgpio associatedReset ""
set_interface_property bgpio ENABLED true
set_interface_property bgpio EXPORT_OF ""
set_interface_property bgpio PORT_NAME_MAP ""
set_interface_property bgpio CMSIS_SVD_VARIABLES ""
set_interface_property bgpio SVD_ADDRESS_GROUP ""

add_interface_port bgpio uart_status status Input 1
add_interface_port bgpio uart_enable enable Output 1

