# TCL File Generated by Component Editor 18.1
# Sat Apr 20 19:54:40 CEST 2024
# DO NOT MODIFY


# 
# SPIQuick "SPIQuick" v1.0
#  2024.04.20.19:54:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module SPIQuick
# 
set_module_property DESCRIPTION ""
set_module_property NAME SPIQuick
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME SPIQuick
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SpeedSPI
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SPI_DMA.v VERILOG PATH SpeedSPI/SPI_DMA.v
add_fileset_file SPI_QCRC16.v VERILOG PATH SpeedSPI/SPI_QCRC16.v
add_fileset_file SPI_QCRC64_ISO.v VERILOG PATH SpeedSPI/SPI_QCRC64_ISO.v
add_fileset_file SPI_QCRC7.v VERILOG PATH SpeedSPI/SPI_QCRC7.v
add_fileset_file SPI_av_irq.v VERILOG PATH SpeedSPI/SPI_av_irq.v
add_fileset_file SPI_av_reader.v VERILOG PATH SpeedSPI/SPI_av_reader.v
add_fileset_file SPI_av_writer.v VERILOG PATH SpeedSPI/SPI_av_writer.v
add_fileset_file SPI_commander.v VERILOG PATH SpeedSPI/SPI_commander.v
add_fileset_file SPI_config.v VERILOG PATH SpeedSPI/SPI_config.v
add_fileset_file SPI_data_buffer.v VERILOG PATH SpeedSPI/SPI_data_buffer.v
add_fileset_file SPI_initizer.v VERILOG PATH SpeedSPI/SPI_initizer.v
add_fileset_file SPI_irq_sleeper.v VERILOG PATH SpeedSPI/SPI_irq_sleeper.v
add_fileset_file SPI_loader.v VERILOG PATH SpeedSPI/SPI_loader.v
add_fileset_file SPI_multiplex.v VERILOG PATH SpeedSPI/SPI_multiplex.v
add_fileset_file SPI_mutex.v VERILOG PATH SpeedSPI/SPI_mutex.v
add_fileset_file SPI_output.v VERILOG PATH SpeedSPI/SPI_output.v
add_fileset_file SPI_read.v VERILOG PATH SpeedSPI/SPI_read.v
add_fileset_file SPI_reader_memory.v VERILOG PATH SpeedSPI/SPI_reader_memory.v
add_fileset_file SPI_registers.v VERILOG PATH SpeedSPI/SPI_registers.v
add_fileset_file SPI_send.v VERILOG PATH SpeedSPI/SPI_send.v
add_fileset_file SPI_starter.v VERILOG PATH SpeedSPI/SPI_starter.v
add_fileset_file SPI_streamer.v VERILOG PATH SpeedSPI/SPI_streamer.v
add_fileset_file SpeedSPI.v VERILOG PATH SpeedSPI/SpeedSPI.v TOP_LEVEL_FILE
add_fileset_file SpeedSPI_card_core.v VERILOG PATH SpeedSPI/SpeedSPI_card_core.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_address address Input 3
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point data_out
# 
add_interface data_out avalon_streaming start
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset reset
set_interface_property data_out dataBitsPerSymbol 8
set_interface_property data_out errorDescriptor ""
set_interface_property data_out firstSymbolInHighOrderBits true
set_interface_property data_out maxChannel 0
set_interface_property data_out readyLatency 0
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out avm_m1_dout data Output 40
add_interface_port data_out avm_m1_ivalid valid Output 1
add_interface_port data_out avm_m1_oready ready Input 1


# 
# connection point com_in
# 
add_interface com_in avalon_streaming end
set_interface_property com_in associatedClock clock
set_interface_property com_in associatedReset reset
set_interface_property com_in dataBitsPerSymbol 8
set_interface_property com_in errorDescriptor ""
set_interface_property com_in firstSymbolInHighOrderBits true
set_interface_property com_in maxChannel 0
set_interface_property com_in readyLatency 0
set_interface_property com_in ENABLED true
set_interface_property com_in EXPORT_OF ""
set_interface_property com_in PORT_NAME_MAP ""
set_interface_property com_in CMSIS_SVD_VARIABLES ""
set_interface_property com_in SVD_ADDRESS_GROUP ""

add_interface_port com_in avs_s2_inout data Input 40
add_interface_port com_in avs_s2_valid valid Input 1
add_interface_port com_in avs_s2_ready ready Output 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint s0
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender avm_s0_irq irq Output 1


# 
# connection point SPIx4
# 
add_interface SPIx4 conduit end
set_interface_property SPIx4 associatedClock clock
set_interface_property SPIx4 associatedReset reset
set_interface_property SPIx4 ENABLED true
set_interface_property SPIx4 EXPORT_OF ""
set_interface_property SPIx4 PORT_NAME_MAP ""
set_interface_property SPIx4 CMSIS_SVD_VARIABLES ""
set_interface_property SPIx4 SVD_ADDRESS_GROUP ""

add_interface_port SPIx4 spi1_sclk spi1_sclk Output 1
add_interface_port SPIx4 spi1_miso spi1_miso Bidir 1
add_interface_port SPIx4 spi1_mosi spi1_mosi Bidir 1
add_interface_port SPIx4 spi1_cs spi1_cs Output 1
add_interface_port SPIx4 spi2_sclk spi2_sclk Output 1
add_interface_port SPIx4 spi2_miso spi2_miso Bidir 1
add_interface_port SPIx4 spi2_mosi spi2_mosi Bidir 1
add_interface_port SPIx4 spi2_cs spi2_cs Output 1
add_interface_port SPIx4 spi3_sclk spi3_sclk Output 1
add_interface_port SPIx4 spi3_miso spi3_miso Bidir 1
add_interface_port SPIx4 spi3_mosi spi3_mosi Bidir 1
add_interface_port SPIx4 spi3_cs spi3_cs Output 1
add_interface_port SPIx4 spi4_sclk spi4_sclk Output 1
add_interface_port SPIx4 spi4_miso spi4_miso Bidir 1
add_interface_port SPIx4 spi4_mosi spi4_mosi Bidir 1
add_interface_port SPIx4 spi4_cs spi4_cs Output 1


# 
# connection point sclk
# 
add_interface sclk clock end
set_interface_property sclk clockRate 0
set_interface_property sclk ENABLED true
set_interface_property sclk EXPORT_OF ""
set_interface_property sclk PORT_NAME_MAP ""
set_interface_property sclk CMSIS_SVD_VARIABLES ""
set_interface_property sclk SVD_ADDRESS_GROUP ""

add_interface_port sclk sclk clk Input 1


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock clock
set_interface_property m1 associatedReset reset
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 maximumPendingWriteTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 CMSIS_SVD_VARIABLES ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 avm_m1_write write Output 1
add_interface_port m1 avm_m1_read read Output 1
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1
add_interface_port m1 avm_m1_readdatavalid readdatavalid Input 1
add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_writedata writedata Output 32
add_interface_port m1 avm_m1_readdata readdata Input 32

